aws_region = "us-east-1"
environment = "dev"
aws_dynamodb_table_name = "project-5-terraform-locks"
github_org = "adamlevi87"
github_repo = "project-5-tf"
aws_s3_bucket_name = "project-5-tf-state"
aws_iam_role_github_actions_name = "project-5-role-for-manual-tf"
project_tag= "project-5"